<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.forwardmeasure.jpa</groupId>
        <artifactId>forwardmeasure-jpa-parent</artifactId>
        <version>${revision}</version>
    </parent>
    <artifactId>forwardmeasure-jpa-liquibase</artifactId>
    <name>ForwardMeasure JPA Liquibase</name>

    <dependencies>
        <dependency>
            <groupId>com.forwardmeasure.database</groupId>
            <artifactId>forwardmeasure-database-migrations-liquibase</artifactId>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>forwardmeasure-jpa-tenancy</artifactId>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.forwardmeasure.testcontainers</groupId>
            <artifactId>forwardmeasure-testcontainers-junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
